language: node_js
node_js: '6'
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
script:
- yarn bootstrap
- yarn lint
- yarn test
deploy:
  provider: heroku
  api_key:
    secure: RDD5ljYjZAVWDHHaN4ruy7maP6ZaOSMOGRPdzaguy41GCUczzbnS8wIVr4KmsGV5U4BOwPBuiwwihp6YHglpLPmilBHW2l/9UMUgoeaxytPL5DSSWq30MoH2iHJr9sKypKmu3HwdZ8Jeb45QBoQJB6loEY0Y+1++4FWipWRADFliZLFaZOiMibI3rAjQKuI21eimNs+bMrVvTq3FW8KfRJO8f7bjl1OD5WQxzfDlJE2UkbqB8bKRBB3pXp/yce6kd8cCCseKE2rRbQvm97XkRbE9a9mTzeG6k7WCIWyZ2xsrIqCmoCRfbvKZSWTG6e8NC2lX2WVIFjv1dtkCFwDdHvFUtCtjIlGgeRlnPnlk5Kiy//a9gfsK6YrKH+oM63m+yVEZ6MzPNdw4/DfDHRqWJkqYN1QyHOQEQjHWC2UbgNmHmiNsqMbsbJbsG3NLBUXeIy4p8NMLPUJbf5Nxtx3sdAbiAG1fEekaYmVIclgumoWCETdej25naHtCdhBpYWz9Z4KY8esJhb/q4hcRZwiuxrIDEOa7Tms/3aSUxItyOa7SKIGr5qbYRCz6gnsNeB4QbKnNBpYrF48EENo5O8/Ujv4PWTufOghS5rvzS650+KKW8mZ/X4u4isbrEM7MctxVBFbUk6vcMWIWBCW+ovex3o/iC143G0yBnVGKwU/yftU=
  app: nxcms-api
